// This component's job will be to render a list of books.
import React, { Component } from 'react';

// The connect property makes the connect function available to this file.
// To forge a connection between app.js and book-list.js we need to import React-Redux pulling a single property from there:
import { connect } from 'react-redux';

// Connection to our action creator selectBook.
import { selectBook } from '../actions/index';

// This function will make sure that the action generated by the action creator actually flows through all the different reducers in the application.
import { bindActionCreators } from 'redux';

// component:
class BookList extends Component {
  renderList() {
    return this.props.books.map((book) => {
      return (
        <li key={ book.title }className="list-group-item">{ book.title }</li>
      );
    });
  }

// container:
  render() {
    return (
      <ul className="list-group col-sm-4">
        {this.renderList()}
      </ul>
    )
  }
}

// This function will take the application state as an argument.  Our state contains: the array of books and the active book.
// If the state ever changes this container will re-render automatically with a new list of books.
function mapStateToProps(state) {
// The object returned here will be availabel to our component(BookList) as this.props.
// books: state.books, is the connection between Redux and this container.
  return {
    books: state.books
  };
}

// The selectBook value is the actual action creator imported above.
// Anything returned from this function will end up as props on the BookList container.
function mapDispatchToProps(dispatch) {
// Whenever selectBook is called, the resullt should be passed to all of our reducers.
// dispatch takes all the actions and funnels them to all the reducers in the application.
// calling this.props.selectBook would call our action.
  return bindActionCreators({ selectBook: selectBook }, dispatch)
}

// When a container file is made do not export the component(BookList), we want to export the container.
// connect takes a (function) and a (component) and produces a container.
//Propmote BookList from a component to a container - it needs to know about this new dispatch method, selectBook.  Make it acailable as a prop.
export default connect(mapStateToProps, mapDispatchToProps)(BookList);
